config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get  'pages/about'

  #Devise
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations:      'users/registrations'
  }
  devise_scope :user do
    get 'password_edit', to: 'users/registrations#password_edit', as: 'password_edit'
    patch 'password_update', to: 'users/registrations#password_update', as: 'password_update'
  end
  
  #Usersリソース、follow/unfollowアクション
  resources :users, only: [:show, :index] do
    member do
      get :follow, :unfollow, :following, :followers, :notification
    end
  end
  
  #Postsリソース
  resources :posts, only: [:index, :create, :destroy]
  
  #Likesリソース
  resources :likes, only: [:show, :create, :destroy]
  
  #Commentsリソース
  resources :comments, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Userモデルに画像を追加する
  mount_uploader :image, ImageUploader
  
  # Postモデルとの関係性
  has_many :posts, dependent: :destroy
  
  # Likeモデルとの関係性
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  
  # Commentモデルとの関係性
  has_many :comments, dependent: :destroy
  
  # Notificationモデルとの関係性
  has_many :notification, dependent: :destroy
  
  # Deviseのモジュール設定
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  # バリデーション
  validates :name,  presence: true, length: {maximum: 20}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, uniqueness: true,
            format: { with: VALID_EMAIL_REGEX }
  validates :bio,   length: {maximum: 100}
  
  # フォロー機能
  acts_as_followable
  acts_as_follower
  
  # current_passwordを外部から読み書き可能にする
  attr_accessor :current_password
  
  # Facebookの情報をUserインスタンスに代入する
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.remote_image_url = auth.info.image
    end
  end

  # ユーザー登録に渡すデータを設定
  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"]) do |user|
        user.attributes = params
      end
    else
      super
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end
  
  # パスワードを変更する
  def password_update
    current_user.assign_attributes(account_update_params)
    if current_user.save
      sign_in(current_user, bypass: true) # 再ログイン
	    redirect_to current_user, notice: 'パスワードを更新しました'
    else
      render :password_edit
    end
  end

  protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end
  
    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end
  
    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end
  
    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
    
    # 編集後にユーザー個別ページへリダイレクト
    def after_update_path_for(resource)
      user_path(current_user)
    end
  
    # 設定変更時にパスワードを求めない
    def update_resource(resource, params)
      resource.update_without_password(params)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # ログインしていない場合ログインページにリダイレクト（Deviseヘルパー）
  before_action :authenticate_user!,
    only: [:show, :follow, :unfollow, :following, :followers, :notification]
  
  def index # おすすめユーザー一覧
    @user    = current_user
    # 自分とフォローユーザーを除いた一覧
    @users   = User.where.not(id: @user.all_following.map(&:id) << @user.id)
                .page(params[:page]).per(6)
    @post    = @user.posts.new if user_signed_in?
    @comment = Comment.new
  end
  
  def show # 個別ページ
    @user    = User.find(params[:id])
    @post    = @user.posts.new if user_signed_in?
    @posts   = @user.posts.order( created_at: "DESC").page(params[:page]).per(9)
    @comment = Comment.new
  end
  
  def follow # フォロー
    @user = User.find(params[:id])
    current_user.follow(@user) # 対象ユーザーをフォロー
    # Ajaxリクエスト
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
  
  def unfollow # フォロー解除
    @user = User.find(params[:id])
    current_user.stop_following(@user) # 対象ユーザーのフォロー解除
    # Ajaxリクエスト
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
  
  def following  # フォロー一覧
    @user  = User.find(params[:id])
    # all_followingでarrayクラスを呼び出すため複雑になってしまっている
    @users = User.where(id: (@user.all_following.map(&:id)))
              .page(params[:page]).per(6)
    @post  = current_user.posts.new if user_signed_in?
  end
  
  def followers # フォロワー一覧
    @user  = User.find(params[:id])
    # followersでarrayクラスを呼び出すため複雑になってしまっている
    @users = User.where(id: (@user.followers.map(&:id)))
              .page(params[:page]).per(6)
    @post  = current_user.posts.new if user_signed_in?
  end
  
  def notification # 通知一覧
    @user    = current_user
    @users   = User.all
    @post    = @user.posts.new if user_signed_in?
    @comment = Comment.new
    @notification = Notification.where(post_id: @user.posts.ids)
                    .order( created_at: "DESC").page(params[:page]).per(6)
    # 開いたとき既読にする
    @notification.update(status: false) 
  end
end

app/views/users/_details.html.slim
/自己紹介がある場合表示
div
  = user.bio if user.bio.present?

/websiteがある場合表示
- if user.website.present?
  div
    span.glyphicon.glyphicon-link aria-hidden="true" 
    = link_to(user.website, user.website)
    
/ログインユーザーの場合
- if user == current_user
  div
    span.glyphicon.glyphicon-pencil aria-hidden="true" 
    = link_to('プロフィールを編集する', edit_user_registration_path)

app/views/users/_follow.html.slim
/Ajax利用のためインスタンス変数のまま使用
- if @user.id != current_user.id
  #follow
    - if current_user.following?(@user)
      div
        /フォロー解除ボタン
        = link_to "フォロー中" , unfollow_user_path(@user), method: :get, class: "btn btn-default btn-block", remote: true
    - else
      div
        /フォローボタン
        = link_to "フォローする", follow_user_path(@user), method: :get, class: "btn btn-success btn-block", remote: true

app/views/users/_intro.html.slim
/_details.html.erbとの統合はできないか？
.user
  div
    = link_to image_tag(user.image.url, alt: "サムネイル画像",class: "sumnail img-circle"), user_path(user)
    = link_to user.name, user_path(user)
  /自己紹介がある場合表示
  - unless user.bio.blank?
    = user.bio.truncate(20)

app/views/users/_users.html.slim
/サイドバー
- if user_signed_in?
  .sidebar.col-md-2.col-md-offset-2.col-xs-10.col-xs-offset-1
    = render partial: 'layouts/sidebar', locals: { user: @user, post: @post }
    
/該当ユーザーの一覧
.col-md-6.col-xs-12
  - if users.any?
    - users.each do |user|
      .col-md-6.col-xs-12
        = render 'intro', user: user
    /ページネーション
    = paginate users
  - else
    .col-md-10.col-md-offset-1
      = link_to '気になるユーザーをフォローしてみましょう!', users_path

app/views/users/follow.js.slim
/JavaScriptと埋め込みRubyを使ってフォローの関係性を作成する
|$("#follow").html("#{escape_javascript(render('users/follow'))}");

app/views/users/followers.html.slim
- provide(:title, "Followers")
= render partial: 'users', locals: { users: @users }

app/views/users/following.html.slim
- provide(:title, "Following")
= render partial: 'users', locals: { users: @users }

app/views/users/index.html.slim
- provide(:title, "Users")
= render partial: 'users', locals: { users: @users }

app/views/users/notification.html.slim
- provide(:title, "Notification")
/サイドバー
- if user_signed_in?
  .sidebar.col-md-2.col-md-offset-2.col-xs-10.col-xs-offset-1
    = render partial: 'layouts/sidebar', locals: { user: @user, post: @post }
    
/ログインユーザーの投稿を表示
.col-md-6.col-xs-12
  - if @notification.present?
    - @notification.each do |notice|
      .col-md-12
        .user
          .col-md-2.col-xs-2
            = link_to image_tag(notice.user.image.url, alt: "サムネイル画像",
                class: 'img-circle'), notice.user
          .col-md-8.col-xs-8
            - if current_user == @user && notice.kind == "like"
              = link_to notice.user.name, notice.user
              | さんが、あなたの投稿をお気に入りに追加しました。
            - elsif current_user == @user && notice.kind == "comment"
              = link_to notice.user.name, notice.user
              | さんが、あなたの投稿にコメントしました。
            = time_ago_in_words notice.created_at
            | 前
          .col-md-2.col-xs-2
            = image_tag notice.post.picture.to_s
  - else
    .col-md-10.col-md-offset-1
      p お気に入り登録やコメントが通知されます。

app/views/users/show.html.slim
- provide(:title, "User")
/サイドバー
- if user_signed_in?
  .sidebar.col-md-2.col-md-offset-2.col-xs-10.col-xs-offset-1
    = render partial: 'layouts/sidebar', locals: { user: @user, post: @post }
    = render partial: 'details', locals: { user: @user }
    
/ログインユーザーの投稿を表示
.col-md-6.col-xs-12
  /投稿画像
  - if @user.posts.present?
    - @posts.each do |post|
      = render partial: 'posts/post', locals: { post: post, comment: @comment }
    /ページネーション
    = paginate @posts
  - else
    まだ投稿がありません。

app/views/users/unfollow.js.slim
/JavaScriptと埋め込みRubyを使ってフォローの関係性を作成する
|$("#follow").html("#{escape_javascript(render('users/follow'))}");