config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get  'pages/about'

  #Devise
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations:      'users/registrations'
  }
  devise_scope :user do
    get 'password_edit', to: 'users/registrations#password_edit', as: 'password_edit'
    patch 'password_update', to: 'users/registrations#password_update', as: 'password_update'
  end
  
  #Usersリソース、follow/unfollowアクション
  resources :users, only: [:show, :index] do
    member do
      get :follow, :unfollow, :following, :followers, :notification
    end
  end
  
  #Postsリソース
  resources :posts, only: [:index, :create, :destroy]
  
  #Likesリソース
  resources :likes, only: [:show, :create, :destroy]
  
  #Commentsリソース
  resources :comments, only: [:create, :destroy]
end

app/views/pages/_landing.html.slim
/ランディングページ背景と紹介文
.text-center
  = image_tag('landing_image.jpg', alt: "ランディングページ画像",
      class: "img-responsive img-rounded")
  br
  p 全ての機能を使うためには、ユーザー登録か必要です（テストユーザー email: test@gmail.com pass: testuser）
  strong ↓ボタンのワンクリックでログイン可能です！
  
  = form_for :user, class: "form-inline", url: session_path(:user) do |f|
    .form-group
      = f.hidden_field :email, value: 'test@gmail.com'
      = f.hidden_field :password, value: 'testuser'
      = f.submit 'テストユーザーでログインする', class: 'btn-info btn-sm'
  
  - resource_class.omniauth_providers.each do |provider|
    = link_to "#{OmniAuth::Utils.camelize(provider)}でログインする",
      omniauth_authorize_path(resource_name, provider), class: 'btn-primary btn-sm'

app/views/pages/about.html.slim
- provide(:title, "About")
.col-md-6.col-md-offset-2
  /利用規約
  h3 このサイトについて
  p インスタグラムクローンアプリです。

app/views/pages/index.html.slim
/サイドバー
- if user_signed_in?
  .sidebar.col-md-2.col-md-offset-2.col-xs-10.col-xs-offset-1
    = render partial: 'layouts/sidebar', locals: { user: @user, post: @post }
    
/ログイン前はランディングページ、ログイン後はタイムライン
- if user_signed_in?
  .col-md-6.col-xs-12
    - if @timeline.present?
      - @timeline.each do |post|
        = render partial: 'posts/post', locals: { post: post, comment: @comment }
      /ページネーション
      = paginate @timeline
    - else
      .col-md-10.col-md-offset-1
        = link_to '気になるユーザーをフォローしてみましょう!', users_path
- else
  .col-md-6.col-md-offset-3
    = render partial: 'landing'