config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get  'pages/about'

  #Devise
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations:      'users/registrations'
  }
  devise_scope :user do
    get 'password_edit', to: 'users/registrations#password_edit', as: 'password_edit'
    patch 'password_update', to: 'users/registrations#password_update', as: 'password_update'
  end
  
  #Usersリソース、follow/unfollowアクション
  resources :users, only: [:show, :index] do
    member do
      get :follow, :unfollow, :following, :followers, :notification
    end
  end
  
  #Postsリソース
  resources :posts, only: [:index, :create, :destroy]
  
  #Likesリソース
  resources :likes, only: [:show, :create, :destroy]
  
  #Commentsリソース
  resources :comments, only: [:create, :destroy]
end

app/views/layouts/_flash.html.slim
/bootstrapのフラッシュを設定
.container-fluid
  .row
    .col-md-6.col-md-offset-3
      - flash.each do |type, msg|
        - if type == "notice"
          .alert.alert-success
            a.close data-dismiss="alert" href="#"  ×
            ul
              li= msg
        - elsif type == "alert"
          .alert.alert-danger
            a.close data-dismiss="alert" href="#"  ×
            ul
              li= msg
        - else
          div class=("alert alert-#{"#{type}"}") 
            a.close data-dismiss="alert" href="#"  ×
            ul
              li= msg

app/views/layouts/_header.html.slim
/メタデータとナビゲーション
header
  nav.navbar.navbar-fixed-top.navbar-default
    .container-fluid
      .navbar-header
        button.navbar-toggle.collapsed data-target="#navbarEexample3" data-toggle="collapse" type="button" 
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href="#" 
          = link_to "Instagram app", root_path,class: "navbar-brand"
      #navbarEexample3.collapse.navbar-collapse
        ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            /検索フォーム
            = search_form_for @q, class: "navbar-form navbar-right",  url: posts_path do |f|
              .form-group
                = f.search_field :content_cont, class: "form-control", placeholder: 'キーワード検索'
                = button_tag type: "submit", class: "btn btn-default btn-sm" do
                  span.glyphicon.glyphicon-search aria-hidden="true" 
            = render partial: 'layouts/links', locals: { notification: notification }
          - else
            li = link_to '新規登録', new_user_registration_path
            li = link_to 'ログイン', new_user_session_path

app/views/layouts/_links.html.slim
/通知ボタン
- if notification.where(status: true).present?
  li.active
    = link_to notification_user_path(current_user) do
      span.glyphicon.glyphicon-bell aria-hidden="true" 
      | 通知
- else
  li
    = link_to notification_user_path(current_user) do
      span.glyphicon.glyphicon-bell aria-hidden="true" 
      | 通知
      
/リンクがドロップダウンする
li.dropdown
  a.dropdown-toggle data-toggle="dropdown" href="#" role="button" 
    = current_user.name
    span.caret
  ul.dropdown-menu role="menu" 
    li
      = link_to current_user do
        span.glyphicon.glyphicon-user aria-hidden="true" 
        | ユーザーページ
    li
      = link_to edit_user_registration_path do
        span.glyphicon.glyphicon-pencil aria-hidden="true" 
        | プロフィール編集
    li
      = link_to like_path(current_user) do
        span.glyphicon.glyphicon-heart aria-hidden="true" 
        | お気に入り一覧
    li
      = link_to users_path do
        span.glyphicon.glyphicon-globe aria-hidden="true" 
        | おすすめユーザー
    li
      = link_to destroy_user_session_path, method: :delete do
        span.glyphicon.glyphicon-log-out aria-hidden="true" 
        | ログアウト

app/views/layouts/_shim.html.slim
/[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]

app/views/layouts/_sidebar.html.slim
/ユーザー情報
li
  = link_to image_tag(user.image.url, alt: "サムネイル画像", class: "sumnail img-circle"), user
  = link_to user.name, user
  
/統計情報
.row
  .col-md-3.col-xs-3.col-xs-offset-1
    a href="#{user_path(user)}" 
      small 投稿
      div= user.posts.count
  .col-md-4.col-xs-4
    a href="#{following_user_path(user)}" 
      small フォロー
      div= user.follow_count
  .col-md-4.col-xs-4
    a href="#{followers_user_path(user)}" 
      small フォロワ
      div= user.followers_count
      
/画像投稿フォーム
- if current_user == user
  = form_for(post) do |f|
    = f.file_field :picture
    span.btn.btn-block
      = f.submit "Post"

/フォローフォーム
li
  = render partial: 'users/follow'

app/views/layouts/_twitter.html.slim
    meta content="summary" name="twitter:card"
    meta content="@bankoo_blog" name="twitter:site"
    meta content="https://bankoo-instagram.herokuapp.com/" property="twitter:url"
    meta content="Instagram_app" property="twitter:title"
    meta content="Instagramを参考して作成した、画像共有サイトです。" property="twitter:description"
    meta content=("#{asset_url 'default.jpg'}") property="twitter:image"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = full_title(yield(:title))
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    = render 'layouts/shim'
    = render 'layouts/twitter'
    = favicon_link_tag('favicon.ico')
  body
    = render partial: 'layouts/flash'
    = render partial: 'layouts/header', locals: { notification: @notification }
    .container-fluid
      .row
        = yield
      .row
        .col-md-8.col-md-offset-2
          = debug(params) if Rails.env.development?